### ISSUE TITLE
Question: How to make predictions over smaller spatial domain, or on a new set of predictor rasters.

### ISSUE THREAD

**Issue by cwaldock1** [iiasa/ibis.iSDM#104]
I have looked through most of the material in the very helpful vignettes and tutorials, so perhaps I have overlooked it, but is there a function/approach to make spatial predictions for a smaller area than the model was build on (or defined in the "distribution" function). For example, I am using data across the whole of europe, but for a project I would like to make predictions for only a small subset of this whole area. For large models or high resolutions, it is a bit inefficient to make the suitability predictions for the whole domain specified in the background object? Is there a way to make prediction on a smaller subset of the full domain, or more generally, on a completely new raster with the same covariates.

Thanks for the great package, its incredible!!
Conor

**Comment by Martin-Jung** [comment]
Hi Conor,

Great to hear that you find the package useful.

- Generally predictions or 'projections' on different/new data are possible by supplying a `SpatRaster` or better `stars` object to the `scenario()` function (see example below).
- Maybe I misunderstood your question, but prediction on different subset of areas (larger or smaller) should be possible if the supplied predictors are of different extent?
- Note that you can even train a SDM without making any predictions at all (using `train(..., inference_only = TRUE)` flag ) and afterwards still project the model on a new covariate set.
- The `distribution()` call has a parameter called `limits`/`limits_method` that allows to limit the prediction surface, for example to areas with data coverage or a minimum convex polygon of all points.
- You can also specifically provide a limits layer to `scenario()` (see below example)

**Possible before, but note small patch on https://github.com/iiasa/ibis.iSDM/commit/b1b52816542a19262514c2e9fe021408d3167346 in `dev` branch.**

Example:
```
library(ibis.iSDM)
library(stars)
background <- terra::rast(system.file('extdata/europegrid_50km.tif', package='ibis.iSDM'))
virtual_points <- sf::st_read(system.file('extdata/input_data.gpkg', package='ibis.iSDM'), 'points',quiet = TRUE)

ll <- list.files(system.file('extdata/predictors_presfuture/',package = "ibis.iSDM",mustWork = TRUE),
                 full.names = T)
# Load the same files future ones
suppressWarnings(
  pred_future <- stars::read_stars(ll) |> stars:::slice.stars('Time', seq(1, 86, by = 10))
)
sf::st_crs(pred_future) <- sf::st_crs(4326)

pred_current <- ibis.iSDM:::stars_to_raster(pred_future, 1)[[1]]
names(pred_current) <- names(pred_future)

# Make a prediction
x <- distribution(background) %>%
  add_biodiversity_poipo(virtual_points, field_occurrence = 'Observed', name = 'Virtual points') %>%
  add_predictors(pred_current, transform = 'scale',derivates = "none") %>%
  engine_glmnet()

modf <- train(x, runname = 'Null', inference_only = F, verbose = T)
plot(modf)
```
![grafik](https://github.com/iiasa/ibis.iSDM/assets/3788377/68092f5a-b625-49c6-ab67-967ca8b77fb1)

```
# Clip to dummy subset area
subs <- terra::crop(background, sf::st_bbox(c("xmin" = 0, "ymin" = 40, "xmax" = 10, "ymax" = 50)))

# Create a projection for a specific area
mod <- scenario(modf, limits = subs) %>%
  add_predictors(env = pred_future, transform = 'scale', derivates = "none") %>%
  project(layer = "mean")

plot(mod)
```
![grafik](https://github.com/iiasa/ibis.iSDM/assets/3788377/fdde1e3a-2a24-4bf4-8659-39c053ec6833)

Hope that helps?

**Comment by cwaldock1** [comment]
Hi Martin,

Thanks for the quick response. Yes, the above is exactly the output i'm looking for.

However, when I copy and run the following code from above in a clean session I get the following error. Until then it all works as you show above. 

`mod <- scenario(modf, limits = subs) %>%
  add_predictors(env = pred_future, transform = 'scale', derivates = "none") %>%
  project(layer = "mean")`

2024-03-15 09:30:59.524318 Adding scenario predictors... 
2024-03-15 09:30:59.524552 Transforming predictors... 
**Error in if (!x %in% names(self$fits)) return(new_waiver()) :    argument is of length zero**

Thanks for any possible assistance. I am using the version installed using `remotes::install_github("IIASA/ibis.iSDM")`. Is it advised to work with the development version? 

Cheers,
Conor

My session info is below: 
R version 4.3.3 (2024-02-29 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

time zone: Europe/Zurich
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] glmnetUtils_1.1.9 glmnet_4.1-8      stars_0.6-4       sf_1.0-15        
[5] abind_1.4-5       ibis.iSDM_0.1.2  

loaded via a namespace (and not attached):
 [1] Matrix_1.6-5       dplyr_1.1.4        compiler_4.3.3     tidyselect_1.2.1  
 [5] Rcpp_1.0.12        parallel_4.3.3     assertthat_0.2.1   splines_4.3.3     
 [9] uuid_1.2-0         lattice_0.22-5     readr_2.1.5        R6_2.5.1          
[13] generics_0.1.3     classInt_0.4-10    shape_1.4.6.1      iterators_1.0.14  
[17] tibble_3.2.1       units_0.8-5        DBI_1.2.2          pillar_1.9.0      
[21] tzdb_0.4.0         rlang_1.1.3        utf8_1.2.4         terra_1.7-71      
[25] cli_3.6.2          withr_3.0.0        magrittr_2.0.3     class_7.3-22      
[29] foreach_1.5.2      grid_4.3.3         rstudioapi_0.15.0  hms_1.1.3         
[33] lifecycle_1.0.4    vctrs_0.6.5        KernSmooth_2.23-22 proxy_0.4-27      
[37] glue_1.7.0         codetools_0.2-19   survival_3.5-8     fansi_1.0.6       
[41] e1071_1.7-14       tools_4.3.3        pkgconfig_2.0.3

**Comment by Martin-Jung** [comment]
Hi, yes please try the dev version via `remotes::install_github("IIASA/ibis.iSDM", "dev")`.
I haven't seen the bug you are reporting before, so could also be worth checking...

**Comment by cwaldock1** [comment]
OK, I installed the development version, and it works as above. Thanks!

**Comment by Martin-Jung** [comment]
Closed. If there is a specific bug related to existing functions, please open a new issue.
