### ISSUE TITLE
Potential issue if more than 2 similar models are integrated as predictors

### ISSUE THREAD

**Issue by mhesselbarth** [iiasa/ibis.iSDM#116]
I am not sure the following model is actually working: 

```
modf <- distribution(background) |>
  add_predictors(pred_current, transform = 'none', derivates = 'none') |>
  add_biodiversity_poipo(virtual_points, field_occurrence = 'Observed', formula = "observed ~ bio01 + bio12") |>
  add_biodiversity_poipo(virtual_points, field_occurrence = 'Observed', formula = "observed ~ crops + primf") |>
  add_biodiversity_poipo(virtual_points, field_occurrence = 'Observed', formula = "observed ~ urban + pastr") |>
  engine_xgboost() |>
  train(method_integration = "predictor")
```

The issue is that the first two datasets are added using the same name, so the final equation is `observed ~ urban + pastr + poipo_Species.._mean + poipo_Species.._mean` which might be a problem given there are not unique variable names

**Comment by Martin-Jung** [comment]
> Can be avoided if the `name` is specified (and different). But we should probably add a check/warning for this. Alternatively, the naming could include e.g. some of the biodiv `id` which should be unique

Yes, was just thinking that checking for the id (which we don't fully make use of) might be the way to go.

**Comment by mhesselbarth** [comment]
Sounds good. I can start implementing this on the `project`-branch since this also affects the projection. 

For all models having several biodiv datasets
1) Check if names are present
2) If yes, check if names are unique
3). If no, use `id` to construct unique names for each dataset
