### ISSUE TITLE
DESCRIPTION

### ISSUE THREAD

**Issue by mhesselbarth** [iiasa/ibis.iSDM#40]
Two questions about the DESCRIPTION

1. Why is `Rcpp` imported? 
2. Why is the `Collate` field needed? I have never seen that before

**Comment by Martin-Jung** [comment]
1) Could be removed indeed. 
2) I did not add this, think `devtools::load_all()` or so did

**Comment by mhesselbarth** [comment]
Okay...I am cleaning the DESCRIPTION a little bit at the moment and trying to make some progress with the warnings on `dev` currently.

I need to read a bi t more on `collate`...seems to be a way to ensure in which way functions are imported...?

**Comment by Martin-Jung** [comment]
Think this can be closed. If there are questions please ask them on slack.
