### ISSUE TITLE
Pipe operator

### ISSUE THREAD

**Issue by mhesselbarth** [iiasa/ibis.iSDM#41]
Currently both pipe operators are used (`%>%`, `|>`).  I would suggest to either

1) Remove pipes completely
2) Stick to one (probably `magrittr` to not have to rely on `R` > 4.0) 

Thoughts?

**Comment by Martin-Jung** [comment]
Yes, this was added at a time where R did not have a separate pipe. Can be removed, but needs to be checked that the pipe is not accidentally used somewhere

**Comment by Martin-Jung** [comment]
`magrittr` dependency removed in https://github.com/iiasa/ibis.iSDM/commit/61dcd1233644e76e5af40db1fe3dd1b96af17114
