### ISSUE TITLE
Helper function to summarize patch and landscape metrics on predicted 

### ISSUE THREAD

**Issue by Martin-Jung** [iiasa/ibis.iSDM#50]
Capturing the idea spinned around during the BEC meeting today. 
Ideally we have some helper function that loads in the namespace of `landscapemetrics` and calculates patch and landscape metrics on outputs of `train`, e.g. `BiodiversityDistribution` objects.

- [ ] Add an inherent function to `DistributionModel` class objects in bdproto-distributionmodel.R names (for example) `summary_patch` or something else easy to interpret
- [ ] Function should calculate a range of "standard" metrics such as average patch size, effective mesh index, average distance between patches etc. 
- [ ] Depending on whethera threshold (binary) has been added (check via `self$get_thresholdvalue` in object), calculate either continious (entropy) or discrete metrics.
- [ ] (optional) Add a separate generic function to address this class function, for example `summarize_patches` or `summarize_landscape` ?
- [ ] Add unit tests

**Relevant reference here:**
Lucas, P. M., González‐Suárez, M., & Revilla, E. (2019). Range area matters, and so does spatial configuration: predicting conservation status in vertebrates. Ecography, 42(6), 1103-1114. https://onlinelibrary.wiley.com/doi/abs/10.1111/ecog.03865

**Comment by mhesselbarth** [comment]
I wonder, in terms of dependencies/imports/suggests and general maintenance as well as scope of this package, if it makes sense to actually provide this as a functionality of `ibis.iSDM` or if it would be better to "just" write a vignette about how to use the outputs in combination with `landscapemetrics` to calculate metrics? 

Another argument for this would be that there are no real "standard" metrics, but it highly depends on data, questions, etc. what metrics to calculate.

**Comment by Martin-Jung** [comment]
As with other optional helper packages i would not add this as a dependency to the description file only as suggestion. Don't think there is a need to write a vignette in this package if there are no build-in functions to use it (people can always combined the outputs with other packages). 
Metrics: Sure agree, maybe an option could be to have a few metrics as "default" parameter vector which can be changed depending on user preferences.

Anyway, just an idea :) If there is no benefit in repeated use and it is easier for our projects to code this up separately from the package (if we make use of this option), also fine with me.

**Comment by mhesselbarth** [comment]
I created a script for our project using the output raster of `ibis.iSDM` (a threshold habitat map) and calculated some landscape metrics (patch size, core area, aggregation index, distance nearest patch, etc.). Given that the output can basically be forwarded directly to `landscapemetrics`, I am more convinced we actually don't need to include this as function within `ibis.iSDM`

**Comment by Martin-Jung** [comment]
Ok
Will close issue for now.
