### ISSUE TITLE
'observed' vs 'Observed' default column name

### ISSUE THREAD

**Issue by simonrolph** [iiasa/ibis.iSDM#73]
Just a small one, inconsistency in default column name:

In `validate` the default column name is 'observed' https://iiasa.github.io/ibis.iSDM/reference/validate.html (although I see that there's future work to be done here so I guess you'll pick this up then)

in `add_pseudoabsence()` etc. it's 'Observed"

**Comment by Martin-Jung** [comment]
Yes, variable names could more be harmonized. I think I figured back then that most uses will probably specify a custom name to column_observed anyhow (rather than renaming their data to 'Observed').

**Comment by Martin-Jung** [comment]
Default changed to "observed" throughout in documentation and default options https://github.com/iiasa/ibis.iSDM/commit/b627a50d0409b4969476f38970f6538faf858c5d
