### ISSUE TITLE
Integration several datasets

### ISSUE THREAD

**Issue by mhesselbarth** [iiasa/ibis.iSDM#78]
In the following example, predictions of the first biodiversity dataset are used as an additional predictor for the second dataset. However, the extracted predicted values are also added to the first dataset. Is there a particular reason for this? As far as I understand it, it should be enough to only add the values to the next following biodiversity dataset?

```
distribution(background) |>
  add_predictors(env = predictors, transform = "scale", derivates = "none") |>
  add_biodiversity_poipo(poipo = virtual_species, field_occurrence = "Observed",
                         formula = formula(paste("observed ~ a + b"))) |>
  add_biodiversity_poipo(poipo = virtual_species, field_occurrence = "Observed",
                         formula = formula(paste("observed ~ c + d"))) |>
  train(method_integration = "predictor")
```

**Comment by Martin-Jung** [comment]
Not quite sure what you mean, but passing on predictions to the next models is the default for engines that don't support joint estimation of multiple datasets, the parameter `method_integration` applies (default: "predictor"). Extracted predictors are in this case added.
- It needs to pass on predictions among multiple steps. One can think of an example where like 3 or more different datasets are added.
- Ultimately the number of predictors in the model object does not matter as long as they are present. Spatial (or temporal) projections only make use of those predictors in the equation (`formula`).

**Comment by mhesselbarth** [comment]
> * It needs to pass on predictions among multiple steps. One can think of an example where like 3 or more different datasets are added.

I understand that and it's done within the loop in `train()` as well as updating the formula object. My question is why in the code example above the extracted predictor values are added to the first data.frame which stores covariates a + b. Doesn't it only require c + d+ prev.prediction but NOT a + b + prev.prediction? For example, the first formula is also not updated using a skip, but the data.frame still is.

**Comment by Martin-Jung** [comment]
> My question is why in the code example above the extracted predictor values are added to the first data.frame which stores covariates a + b. Doesn't it only require c + d+ prev.prediction but NOT a + b + prev.prediction? 

If at some point we want `project()` to reproduce the formula of `train()` we would need all the predictors in the dataset (unless full models are saved in the object, which would be even larger in size than additional columns).

> Even if its not particular used during any later predictions, it adds unnecessary to the data.

if you think it is critical to fix, and it does not affect the functionality of `method_integration="predictor"` , then feel free to commit a fix.

**Comment by Martin-Jung** [comment]
I think this can be closed due to https://github.com/iiasa/ibis.iSDM/pull/119 right?

**Comment by mhesselbarth** [comment]
I think so yes
