### ISSUE TITLE
Possible typo in FAQ

### ISSUE THREAD

**Issue by jeffreyhanson** [iiasa/ibis.iSDM#92]
The FAQ is great! Brilliant idea including this in the documentation. When reading it, I noticed that the FAQ has the [following text](https://github.com/iiasa/ibis.iSDM/blob/1098bf07ac5af9b2ecf70dfd328f11c79773c512/vignettes/articles/08_frequently-asked-questions.Rmd#L215-L219):

```
<details>
<summary><b>There are too many messages. How can I run `ibis.iSDM` more verbosely ?</b>
</summary>

There are two options that can be enabled to reduce the number of messages:
```

I think  "more verbosely" should be "less verbosely"?

**Comment by Martin-Jung** [comment]
Ha, indeed. To be corrected (generally lots of work on the documentation :D )
