### ISSUE TITLE
Error with `train()` when using INLA with `add_biodiversity_poipa()` and weights

### ISSUE THREAD

**Issue by jeffreyhanson** [iiasa/ibis.iSDM#93]
I'm trying to fit a species distribution model that has weighted presence/absence data using the inlabru engine. I've included a reprex below that uses the example data. It seems that the code works fine if weights are not specified, but I get an error about void binomial data if weights are specified? Sorry, it's not clear to me what I'm doing wrong, and googling the error message suggests that maybe the input data are [formatted incorrectly](https://groups.google.com/g/r-inla-discussion-group/c/PfcmvqPowW8)?

```
# load package
library(ibis.iSDM)
library(magrittr)

# load data
bg_data <- 
  system.file("extdata/europegrid_50km.tif", package = "ibis.iSDM") %>%
  terra::rast()
spp_data <- 
  system.file("extdata/input_data.gpkg",package = "ibis.iSDM") %>%
  sf::read_sf("points") 
env_data <-
  system.file("extdata/predictors/", package = "ibis.iSDM") %>%
  dir(full.names = TRUE) %>%
  terra::rast()

# create presence/absence species data
## to do this, we will create a new column (value) with random 1s/
spp_data$value <- round(runif(nrow(spp_data)))

# add column to species data with weights
spp_data$weight <- runif(nrow(spp_data), 0.6, 0.99)

# create model specification
mod <- 
  distribution(bg_data) %>%
  add_biodiversity_poipa(
    spp_data,
    name = "observations",
    weight = spp_data$weight,
    field_occurrence = "value"
  ) %>%
  add_predictors(
    env = env_data,
    transform = "scale", derivates = "none"
  ) %>%
  engine_inlabru()

# train model
fit <- train(mod)
```

```
#> [Setup] 2024-01-31 11:35:10.956378 | Provide a background with a valid projection!
#> [Setup] 2024-01-31 11:35:10.972144 | Creating distribution object...
#> [Setup] 2024-01-31 11:35:10.986562 | Adding poipa dataset...
#> [Setup] 2024-01-31 11:35:11.062839 | Adding predictors...
#> [Setup] 2024-01-31 11:35:11.063866 | Transforming predictors...
#> [Estimation] 2024-01-31 11:35:11.1079 | Collecting input parameters.
#> [Estimation] 2024-01-31 11:35:11.143882 | Adding engine-specific parameters.
#> [Estimation] 2024-01-31 11:35:11.9109 | Engine setup.
#> [Estimation] 2024-01-31 11:35:11.940022 | Starting fitting.
#> iinla: Iteration 1 [max:10]
#> 
#> 
#> *** ERROR ***   INLA.Data1: Binomial data[0] (nb,y) = (0.730844,1) is void
#> 
#> 
#> Error in inla.inlaprogram.has.crashed() : 
#>   The inla-program exited with an error. Unless you interupted it yourself, please rerun with verbose=TRUE and check the output carefully.
#>   If this does not help, please contact the developers at <help@r-inla.org>.
#> 
#>  *** inla.core.safe:  inla.program has crashed: rerun to get better initial values. try=1/1 
#> 
#> 
#> *** ERROR ***   INLA.Data1: Binomial data[0] (nb,y) = (0.730844,1) is void
#> 
#> 
#> Error in inla.inlaprogram.has.crashed() : 
#>   The inla-program exited with an error. Unless you interupted it yourself, please rerun with verbose=TRUE and check the output carefully.
#>   If this does not help, please contact the developers at <help@r-inla.org>.
#> Warning in iinla(model = info[["model"]], lhoods = info[["lhoods"]], options = info[["options"]]) :
#>   iinla: Problem in inla: Error in inla.core.safe(formula = formula, family = family, contrasts = contrasts,  : 
#>   *** Failed to get good enough initial values. Maybe it is due to something else.
#> iinla: Problem in inla: 1: train(mod)
#> 2: train(mod)
#> 3: x$engine$train(model, settings)
#> 4: res(x, ...)
#> 5: try({
#>        fit_bru <- inlabru::bru(components = comp, likelihoods, options = options)
#>    }, silent = FALSE)
#> 6: tryCatch(expr, error = function(e) {
#>        call <- conditionCall(e)
#>        if (!is.null(call)) {
#>            if (identical(call[[1L]], quote(doTryCatch))) 
#>                call <- sys.call(-4L)
#>            dcall <- deparse(call, nlines = 1L)
#>            prefix <- paste("Error in", dcall, ": ")
#>            LONG <- 75L
#>            sm <- strsplit(conditionMessage(e), "\n")[[1L]]
#>            w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")
#>            if (is.na(w)) 
#>                w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L], 
#>                    type = "b")
#>            if  [... truncated]
#> iinla: Giving up and returning last successfully obtained result for diagnostic purposes.
#> Error in res(x, ...) : 
#>   Model did not converge. Try to simplify structure and check priors
```

Also, here's my session info if it's useful (running latest GitHub version of ibis.iSDM):

```
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /opt/R/R-4.3.1/lib/R/lib/libRblas.so 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Pacific/Auckland
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] magrittr_2.0.3  ibis.iSDM_0.1.1

loaded via a namespace (and not attached):
 [1] Matrix_1.6-5       crayon_1.5.2       dplyr_1.1.4        compiler_4.3.1    
 [5] renv_1.0.3         tidyselect_1.2.0   Rcpp_1.0.12        MatrixModels_0.5-3
 [9] parallel_4.3.1     assertthat_0.2.1   splines_4.3.1      uuid_1.2-0        
[13] yaml_2.3.8         lattice_0.21-8     plyr_1.8.9         R6_2.5.1          
[17] generics_0.1.3     classInt_0.4-10    inlabru_2.10.1     sf_1.0-15         
[21] iterators_1.0.14   tibble_3.2.1       fmesher_0.1.5      units_0.8-5       
[25] proto_1.0.0        DBI_1.2.1          pillar_1.9.0       rlang_1.1.3       
[29] utf8_1.2.4         sp_2.1-2           terra_1.7-65       cli_3.6.2         
[33] withr_3.0.0        class_7.3-22       foreach_1.5.2      grid_4.3.1        
[37] INLA_23.09.09      lifecycle_1.0.4    vctrs_0.6.5        KernSmooth_2.23-21
[41] proxy_0.4-27       glue_1.7.0         codetools_0.2-19   zoo_1.8-12        
[45] fansi_1.0.6        e1071_1.7-14       tools_4.3.1        pkgconfig_2.0.3   
```

**Comment by jeffreyhanson** [comment]
I'm looking into the code to see if I can understand what's going on. Sorry in advance if I'm barking up the wrong tree, but it looks like weights are handled in [inla using the `Ntrials` parameter](https://github.com/iiasa/ibis.iSDM/blob/1098bf07ac5af9b2ecf70dfd328f11c79773c512/R/engine_inlabru.R#L500-L506). So, for example, a weight of 2 for presence/absence values would indicate that two samples were observed. Assuming that's right, then I can see why I might be running into issues. The weights I have are non-integer values ranging between zero and one that indicate a relative level of support for observation. Is there some way to accomodate such weights in ibis.iSDM?

I was looking into the INLA/inlabru documentation to see if there would be some way to achieve this. It seems that a `weights` parameter can be used to weight the influence of different samples on the model's loglikelihood (e.g., in `INLA::inla` or `inlabru::like`) which seems promising. Do you think it would be possible to update the package to add such functionality? After looking on the INLA forums, it does seem that user weights would need to be rescaled/corrected to ensure correct results ([see here](https://groups.google.com/g/r-inla-discussion-group/c/OmI5ApDpI60/m/_S7j9HouAAAJ)):

```
corrected_weights = raw_weights / sum(raw_weights) * length(raw_weights)
```

**Comment by Martin-Jung** [comment]
Thanks for reporting and checking, will try to look into this as soon as I am able to (out of office next couple of weeks).

**Comment by jeffreyhanson** [comment]
Awesome - thank you very much! It would be extremely useful for me if this could be implemented, so let me know if there's anything else I can do to help?

**Comment by Martin-Jung** [comment]
Yeah, I think I need to recheck the weights and how they are handled, which has changed a bit since INLA was added as we now support for many engines also biodiversity feature specific weights (via `add_biodiversity_xxxx(..., weight = 2))`.
Rescaling def. makes sense intuitively. For binomial poipa data by default the weighting ensures a downweighted if absenses / presences are unbalanced. For Poisson point-process models the weight is reflective of the area over which is integrated. For integrated models however the behaviour is slightly different.
The recently published [RISDM package](https://nsojournals.onlinelibrary.wiley.com/doi/full/10.1111/ecog.06964) also has a INLA (not inlabru) solution implemented that might be worth checking. 
Any PR are welcome of course :) (recent work on `dev` branch)

**Comment by jeffreyhanson** [comment]
Thanks for explaining all this!

Yeah, in my partiuclar case, I have (somewhat reasonable) estimates for the sensitivity and specificity (in other words, false-negative and false-positive rates) of the presence/absence data and the presence-only data. I intend to use these estimates to calculate sample/observation weights for the model fitting (e.g., for some species, the false-positive weight is much lower than the false negative rate, and the presence/absence data generally have lower false-negative rate than the presence-only data) and subsequently model evaluation (to account for imperfect detection when trying to understand how good the models are). So, it sounds like calculating/updating the weights might be a bit trickier for the Poisson point process models? Good to know.

Thanks for recommending RISDM - I didn't know about that. Quickly looking over the code, it doesn't seem like it supports sample/observation specific weights though.

Great - I'll take a look and see what I can do for implementing the functionality. Just to check, should I wait for any impending PRs to be merged into the dev branch before I start?

**Comment by Martin-Jung** [comment]
Default behaviour for `engine_inlabru` now changed in https://github.com/iiasa/ibis.iSDM/commit/7a44ad2f3a64d2f412454b0c299eb7518e4c65a3
Basically added `weights` as an additional parameter to the `like` function which seems to work.
Also implemented the standardization suggested above for this case. 

Think that fixes the issue, feel free to reopen if not.

**Comment by jeffreyhanson** [comment]
Awesome - thank you very much for this! I'll have a play with this and let you know how I go.
